# Generated by Django 4.2.7 on 2023-12-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, null=True)),
                ("content", models.TextField(null=True)),
                ("author", models.CharField(max_length=255, null=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="images")),
                ("date_added", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
