# Generated by Django 4.2.7 on 2023-12-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="authour",
            new_name="author",
        ),
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
        migrations.AddField(
            model_name="blog",
            name="read_time",
            field=models.IntegerField(null=True),
        ),
    ]
