# Generated by Django 4.2.7 on 2023-12-20 22:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_rename_authour_blog_author_blog_image_blog_read_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="read_time",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="tags",
        ),
    ]
