# Generated by Django 4.2.7 on 2023-12-24 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("date_added", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255, null=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", max_length=5000, null=True
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "num_of_bedrooms",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, null=True
                    ),
                ),
                (
                    "num_of_bathrooms",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, null=True
                    ),
                ),
                ("sqft", models.IntegerField(default=0, null=True)),
                ("address", models.CharField(max_length=255, null=True)),
                ("city", models.CharField(max_length=255, null=True)),
                ("state", models.CharField(max_length=255, null=True)),
                ("zip_code", models.IntegerField(null=True)),
                ("amenities", models.CharField(max_length=255, null=True)),
                ("listing_status", models.CharField(max_length=255, null=True)),
                ("date_added", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="realEstateApp.property",
                        to_field="slug",
                    ),
                ),
            ],
        ),
    ]
