# Generated by Django 4.2.7 on 2023-12-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("realEstateApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
