# Generated by Django 4.2.7 on 2023-12-24 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("realEstateApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyimage",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="realEstateApp.property",
            ),
        ),
    ]
