# Generated by Django 4.2.7 on 2023-12-06 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("realEstateApp", "0002_rename_image_property_property_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="property_images",
        ),
        migrations.AlterField(
            model_name="propertyimage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="propertyimage",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="realEstateApp.property"
            ),
        ),
    ]
