# Generated by Django 4.2.7 on 2023-12-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("realEstateApp", "0003_remove_property_property_images_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyimage",
            name="image",
            field=models.ImageField(upload_to="images"),
        ),
    ]
