# Generated by Django 4.2.7 on 2023-12-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("realEstateApp", "0004_alter_propertyimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="images",
            field=models.ManyToManyField(
                related_name="images", to="realEstateApp.propertyimage"
            ),
        ),
        migrations.AlterField(
            model_name="propertyimage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
