# Generated by Django 4.2.7 on 2023-12-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("realEstateApp", "0005_property_images_alter_propertyimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyimage",
            name="image",
            field=models.ImageField(null=True, upload_to="images"),
        ),
    ]
