# Generated by Django 4.2.7 on 2023-12-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "realEstateApp",
            "0007_remove_property_images_alter_propertyimage_image_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyimage",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
