# Generated by Django 4.2.7 on 2023-12-07 23:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("realEstateApp", "0012_category_userfavorites_booking"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userfavorites",
            name="property",
        ),
        migrations.RemoveField(
            model_name="userfavorites",
            name="user",
        ),
        migrations.DeleteModel(
            name="Booking",
        ),
        migrations.DeleteModel(
            name="UserFavorites",
        ),
    ]
