# Generated by Django 4.2.7 on 2023-12-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("realEstateApp", "0002_alter_property_description"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="favorite_properties",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="custom_user_favorite_properties",
                to="realEstateApp.property",
            ),
        ),
    ]
